"""Create newsletters table

Revision ID: 611e30159775
Revises: be3f72f81f03
Create Date: 2024-03-24 17:06:11.938736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611e30159775'
down_revision = 'be3f72f81f03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
